#reset; ./merger.pl seq.fasta *.xml; ./xml_image_new.pl xmlPos/XMLpos.xml seq.fasta contig.fasta

reset; ./merger.pl R265_c_neoformans.fasta	blast_jobbins2010_vs_r265.blast.xml crypto_out.maf.nd.map.ref.xml; ./xml_image_new.pl xmlPos/R265_c_neoformans_blast_jobbins2010_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.xml R265_c_neoformans.fasta crypto_out.maf.fasta 1>xmlPos/R265_c_neoformans_blast_jobbins2010_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.log 2>xmlPos/R265_c_neoformans_blast_jobbins2010_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.err
reset; ./merger.pl R265_c_neoformans.fasta	blast_literature_vs_r265.blast.xml  crypto_out.maf.nd.map.ref.xml; ./xml_image_new.pl xmlPos/R265_c_neoformans_blast_literature_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.xml  R265_c_neoformans.fasta crypto_out.maf.fasta 1>xmlPos/R265_c_neoformans_blast_literature_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.log  2>xmlPos/R265_c_neoformans_blast_literature_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.err
reset; ./merger.pl R265_c_neoformans.fasta	blast_liu2008_vs_r265.blast.xml     crypto_out.maf.nd.map.ref.xml; ./xml_image_new.pl xmlPos/R265_c_neoformans_blast_liu2008_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.xml     R265_c_neoformans.fasta crypto_out.maf.fasta 1>xmlPos/R265_c_neoformans_blast_liu2008_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.log     2>xmlPos/R265_c_neoformans_blast_liu2008_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.err
reset; ./merger.pl R265_c_neoformans.fasta	blast_microarray_positive.xml       crypto_out.maf.nd.map.ref.xml; ./xml_image_new.pl xmlPos/R265_c_neoformans_blast_microarray_positive_crypto_out.maf.nd.map.ref.XMLpos.xml       R265_c_neoformans.fasta crypto_out.maf.fasta 1>xmlPos/R265_c_neoformans_blast_microarray_positive_crypto_out.maf.nd.map.ref.XMLpos.log       2>xmlPos/R265_c_neoformans_blast_microarray_positive_crypto_out.maf.nd.map.ref.XMLpos.err
reset; ./merger.pl R265_c_neoformans.fasta	blast_noble2010_vs_r265.blast.xml   crypto_out.maf.nd.map.ref.xml; ./xml_image_new.pl xmlPos/R265_c_neoformans_blast_noble2010_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.xml   R265_c_neoformans.fasta crypto_out.maf.fasta 1>xmlPos/R265_c_neoformans_blast_noble2010_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.log   2>xmlPos/R265_c_neoformans_blast_noble2010_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.err
reset; ./merger.pl R265_c_neoformans.fasta	blast_r265Genes_vs_r265.blast.xml   crypto_out.maf.nd.map.ref.xml; ./xml_image_new.pl xmlPos/R265_c_neoformans_blast_r265Genes_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.xml   R265_c_neoformans.fasta crypto_out.maf.fasta 1>xmlPos/R265_c_neoformans_blast_r265Genes_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.log   2>xmlPos/R265_c_neoformans_blast_r265Genes_vs_r265.blast_crypto_out.maf.nd.map.ref.XMLpos.err

#reset; ./merger.pl seq.fasta *.xml; ./xml_image_new.pl xmlPos/XMLpos.xml seq.fasta contig.fasta
